# DO NOT MANUALLY EDIT THIS FILE, USE 'make env_lock' INSTEAD
name: OPA_DPO
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.6
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libpng=1.6.42
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.5
  - libzlib=1.2.13
  - markupsafe=2.1.5
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=23.2
  - pillow=9.4.0
  - pip=23.0.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.1.0
  - sympy=1.12
  - tbb=2021.11.0
  - tk=8.6.13
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing_extensions=4.9.0
  - urllib3=2.2.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.21.0
      - adal==1.2.7
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - applicationinsights==0.11.10
      - argcomplete==3.2.2
      - arrow==1.2.3
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - azure-ai-ml==1.13.0
      - azure-common==1.1.28
      - azure-core==1.30.0
      - azure-graphrbac==0.61.1
      - azure-identity==1.15.0
      - azure-mgmt-authorization==4.0.0
      - azure-mgmt-containerregistry==10.3.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-keyvault==10.3.0
      - azure-mgmt-network==25.1.0
      - azure-mgmt-resource==23.0.1
      - azure-mgmt-storage==21.1.0
      - azure-storage-blob==12.10.0
      - azure-storage-file-datalake==12.6.0
      - azure-storage-file-share==12.15.0
      - azureml==0.2.7
      - azureml-automl-core==1.54.0
      - azureml-core==1.54.0.post1
      - azureml-dataprep==4.12.10
      - azureml-dataprep-native==38.0.0
      - azureml-dataprep-rslex==2.19.8
      - azureml-dataset-runtime==1.54.0.post1
      - azureml-mlflow==1.55.0
      - azureml-pipeline==1.54.0
      - azureml-pipeline-core==1.54.0
      - azureml-pipeline-steps==1.54.0
      - azureml-sdk==1.54.0
      - azureml-telemetry==1.54.0
      - azureml-tensorboard==1.54.0
      - azureml-train-automl-client==1.54.0.post1
      - azureml-train-core==1.54.0
      - azureml-train-restclients-hyperdrive==1.54.0
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.1.2
      - bert-score==0.3.13
      - bitsandbytes==0.41.0
      - black==23.3.0
      - blinker==1.7.0
      - blis==0.7.11
      - cachetools==5.3.2
      - catalogue==2.0.10
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.1.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - comm==0.2.1
      - conda-merge==0.2.0
      - confection==0.1.4
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cryptography==41.0.7
      - cycler==0.12.1
      - cymem==2.0.8
      - dataclasses-json==0.6.4
      - datasets==2.14.7
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepspeed==0.9.5
      - dill==0.3.7
      - distlib==0.3.8
      - distro==1.9.0
      - docker==6.1.3
      - docker-pycreds==0.4.0
      - dotnetcore2==3.1.23
      - einops==0.6.1
      - einops-exts==0.0.4
      - emoji==2.10.1
      - entrypoints==0.4
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - f1chexbert==0.0.2
      - fastapi==0.109.2
      - flake8==6.0.0
      - flask==3.0.2
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fschat==0.2.36
      - fsspec==2023.10.0
      - fusepy==3.0.1
      - gitdb==4.0.11
      - gitpython==3.1.32
      - google-api-core==2.17.1
      - google-auth==2.28.0
      - googleapis-common-protos==1.62.0
      - greenlet==3.0.3
      - grpcio==1.60.1
      - gunicorn==21.2.0
      - h11==0.14.0
      - h5py==3.10.0
      - hi-ml-azure==0.4.1
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.17.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - identify==2.5.35
      - imageio==2.34.0
      - importlib-metadata==7.0.1
      - iniconfig==2.0.0
      - ipykernel==6.29.2
      - ipython==8.21.0
      - isodate==0.6.1
      - iterative-stratification==0.1.7
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jeepney==0.8.0
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpickle==3.0.2
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - knack==0.11.0
      - langchain==0.1.4
      - langchain-community==0.0.20
      - langchain-core==0.1.23
      - langchain-openai==0.0.5
      - langcodes==3.3.0
      - langsmith==0.0.87
      - lazy-loader==0.3
      - lightning-utilities==0.10.1
      - loguru==0.7.2
      - mako==1.3.2
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markdown2==2.4.12
      - marshmallow==3.20.2
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mlflow==2.10.2
      - mlflow-skinny==2.10.2
      - mock==5.1.0
      - msal==1.26.0
      - msal-extensions==1.0.0
      - msrest==0.7.1
      - msrestazure==0.6.4
      - multidict==6.0.5
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - mypy==1.3.0
      - mypy-extensions==1.0.0
      - ndg-httpsclient==0.5.1
      - nest-asyncio==1.6.0
      - nh3==0.2.15
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==1.10.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencensus-ext-azure==1.1.13
      - pandas==2.2.0
      - pandas-stubs==2.0.1.230501
      - param==1.13.0
      - paramiko==3.4.0
      - parso==0.8.3
      - pathlib-abc==0.1.1
      - pathspec==0.12.1
      - pathy==0.11.0
      - peft==0.5.0
      - pexpect==4.9.0
      - pipdeptree==2.14.0
      - pkginfo==1.9.6
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - portalocker==2.8.2
      - pre-commit==3.3.1
      - preshed==3.0.9
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pydantic==1.10.14
      - pydash==7.0.5
      - pydicom==2.4.4
      - pyflakes==3.0.1
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pynacl==1.5.0
      - pyopenssl==23.3.0
      - pyparsing==3.1.1
      - pytest==7.4.0
      - pytest-lazy-fixture==0.6.3
      - python-dateutil==2.8.2
      - pytorch-lightning==2.2.0.post0
      - pytz==2023.4
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - querystring-parser==1.2.4
      - radgraph==0.0.9
      - referencing==0.33.0
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.7.0
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.18.0
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.2
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.12.0
      - secretstorage==3.3.3
      - sentencepiece==0.1.99
      - sentry-sdk==1.40.4
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - simpleitk==2.3.1
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - spacy==3.6.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.27
      - sqlparse==0.4.4
      - srsly==2.4.8
      - stack-data==0.6.3
      - stanza==1.5.0
      - starlette==0.36.3
      - strictyaml==1.7.3
      - svgwrite==1.4.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - thinc==8.1.12
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - tiktoken==0.5.2
      - timm==0.6.13
      - tokenizers==0.14.1
      - tomli==2.0.1
      - torchmetrics==1.3.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - transformers==4.34.1
      - typer==0.9.0
      - types-pillow==10.2.0.20240213
      - types-pytz==2024.1.0.20240203
      - types-tqdm==4.66.0.20240106
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uvicorn==0.27.1
      - virtualenv==20.25.0
      - wandb==0.16.3
      - wasabi==1.1.2
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.9.4
      - zipp==3.17.0
