defaults:
  - llava_training_base
  - override checkpoints: llava-7b-v1.5
  - override image_checkpoints: clip-336
  - _self_

model:
  mm_projector_type: "mlp2x_gelu"
  policy_model_name_or_path: Optional[str] = field(default="liuhaotian/llava-v1.5-7b")
  trust_remote_code: True
  base_model_name: Optional[str] = field(default="liuhaotian/llava-v1.5-7b")
  version: "v1"
  freeze_backbone: False
  tune_mm_mlp_adapter: True
  vision_tower: null
  mm_vision_select_layer: -2
  pretrain_mm_mlp_adapter: null
  mm_use_im_start_end: False
  mm_use_im_patch_token: False
  mm_vision_select_feature: "patch"

training:
  top_k: 0
  top_p: 1.0
  phase: 0
  sample_num: 5120
  norm_maintain_32: True
  lora_with_projector: False
  ddp_backend: null
  ddp_find_unused_parameters: null
  deepspeed: null
  bits: 16
  cache_dir: null
  truncate_tokens: null
  truncate_after: null
  clean_tokens_after_eos: False
  suppress_eos_at_generation: False
  total_epochs: 1
  rollout_batch_size: 512
  step_batch_size: 256
  rollout_per_device_batch_size: 32
  step_per_device_batch_size: 2
  reward_model_per_device_batch_size: null
  noptepochs: 2
  temperature: 1.0
  eval_batches: 256
  save_steps_extra: null
  query_len: 128
  response_len: 384
  model_max_length: 1024
  full_finetune: False
  adam8bit: False
  report_to: "tensorboard"
  resume_dir: null
  output_dir: "./output"
  optim: "paged_adamw_32bit"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  weight_decay: 0.0
  learning_rate: 0.0002
  remove_unused_columns: False
  max_grad_norm: 0.3
  gradient_checkpointing: True
  do_train: True
  lr_scheduler_type: "constant"
  logging_steps: 10
  group_by_length: True
  save_strategy: "steps"
  save_steps: 250
  save_total_limit: 40
  resume_from_training: False
  reward_prompt_file: null
  image_to_caption_file: null
  warmup_steps: null
  freeze_mm_mlp_adapter: False
  max_step: 300
  add_missing: True

data:
  train_splits: null
  stop_token: null
  lazy_preprocess: False
  is_multimodal: False
  image_folder: null
  data_path: null
  image_aspect_ratio: "square"
  image_grid_pinpoints: null

